version: '3.7'

services:
  database:
    image: postgres
    restart: always
    container_name: 'database'
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user_baseoutside
      - POSTGRES_PASSWORD=Leo175033
      - POSTGRES_DB=baseoutside
      
    volumes:
      - pgdata:/data/postgres

    networks:
      - production

      
  app:
    build: .
    container_name: baseoutside
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app


    networks:
      - production
    depends_on:
      - database

volumes:
  pgdata:
    driver: local

networks:
  production:
    driver: bridge

