version: '3.7'

services:
  app:
    build: .
    container_name: baseoutsidecker
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    
  mysql:
    image: mysql:latest
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=Leo175033
    - MYSQL_DATABASE=docker
    ports:
    - 3307:3306